### ISSUE TITLE
Developing an artwork rendering pipeline

### ISSUE THREAD

**Issue by Schofje** [open5e/open5e-image-generation#2]
### Folder structure

- [ ] Sort all the blend files in their corresponding folders
- [ ] Render to a specific path based on the model's name
- [ ] Develop a folder structure that allows for an editorial process

### Inside Blender
- [ ] Make an environment that allows the model and light to rotate per increment
- [x] Lock the model in the bounding box
- [ ] The bounding box is scaled up to the frame plus 10 pixels to the edge of the image

**Comment by eepMoody** [comment]
This is now complete!
